<?php
 /*
 * This file is part of WHATPANEL.
 *
 * @package     WHAT PANEL – Web Hosting Access Terminal Panel.
 * @copyright   2023-2024 Version Next Technologies and MadPopo. All rights reserved.
 * @license     BSL; see LICENSE.txt
 * @link        https://www.version-next.com
 */
$l['invoice'] = 'Rechnung';
$l['estimate'] = 'Angebot';
$l['estimate_cost'] = 'Geschätzte Kosten';
$l['reference_no'] = 'Referenz';
$l['date_issued'] = 'Rechnungsdatum';
$l['due_date'] = 'Fälligkeitsdatum';
$l['from'] = 'Auftragnehmer';
$l['to'] = 'Auftraggeber';

$l['item_name'] = 'Produkt';
$l['amount'] = 'Menge';
$l['vat'] = 'Steuer';
$l['tax'] = 'Steuer';
$l['price'] = 'Preis';
$l['discount'] = 'Rabatt';
$l['total'] = 'Gesamt';
$l['paid'] = 'Bezahlt';
$l['balance_due'] = 'Rechnugnsbetrag';

$l['payment_information'] = 'Zahlungsinformation';
$l['notes'] = 'Notizen';
$l['partially_paid'] = 'Zum Teil bezahlt';
$l['fully_paid'] = 'Komplett bezahlt';
$l['not_paid'] = 'Nicht bezahlt';
$l['draft'] = 'Entwurf';
$l['accepted'] = 'Akzeptieren';
$l['declined'] = 'Ablehnen';
$l['pending'] = 'Anstehend';

$l['page'] = 'Seite';
$l['page_of'] = 'von';

$l['estimate_date'] = 'Estimate Date';
$l['valid_until'] = 'Valid Until';