<?php
 /*
 * This file is part of WHATPANEL.
 *
 * @package     WHAT PANEL – Web Hosting Access Terminal Panel.
 * @copyright   2023-2024 Version Next Technologies and MadPopo. All rights reserved.
 * @license     BSL; see LICENSE.txt
 * @link        https://www.version-next.com
 */
$l['invoice'] = 'Fatura';
$l['reference_no'] = 'Ref No';
$l['date_issued'] = 'Verildiği Tarih';
$l['due_date'] = 'Son Tarih';
$l['from'] = 'Bizim bilgi';
$l['to'] = 'Faturalandırma adresi';
$l['item_name'] = 'Adı';
$l['amount'] = 'Miktar';
$l['vat'] = 'KDV';
$l['tax'] = 'Vergi';
$l['price'] = 'Fiyat';
$l['discount'] = 'İndirim';
$l['total'] = 'Toplam';
$l['paid'] = 'Ödenmiş';
$l['balance_due'] = 'Ödenecek Bakiye';
$l['payment_information'] = 'Ödeme Bilgileri';
$l['notes'] = 'Not';
$l['partially_paid'] = 'Kısmi';
$l['fully_paid'] = 'Tamamen Ödenmiş';
$l['not_paid'] = 'Ödenmeyen';
$l['draft'] = 'Taslak';
$l['accepted'] = 'Kabul edilen';
$l['declined'] = 'Reddedilen';
$l['pending'] = 'Bekliyor';
$l['page'] = 'Sayfa';
$l['page_of'] = 'of';
