<?php
 /*
 * This file is part of WHATPANEL.
 *
 * @package     WHAT PANEL – Web Hosting Access Terminal Panel.
 * @copyright   2023-2024 Version Next Technologies and MadPopo. All rights reserved.
 * @license     BSL; see LICENSE.txt
 * @link        https://www.version-next.com
 */
$l['invoice'] = 'Invoice';
$l['reference_no'] = 'Ref No';
$l['date_issued'] = 'Date Issued';
$l['due_date'] = 'Deadline';
$l['from'] = 'Our information';
$l['to'] = 'Billing to';
$l['item_name'] = 'Name';
$l['amount'] = 'Amount';
$l['vat'] = 'VAT';
$l['tax'] = 'Tax';
$l['price'] = 'Price';
$l['discount'] = 'Discount';
$l['total'] = 'Total';
$l['paid'] = 'Paid';
$l['balance_due'] = 'Balance Due';
$l['payment_information'] = 'Payment Information';
$l['notes'] = 'Notes';
$l['partially_paid'] = 'Partial';
$l['fully_paid'] = 'Fully Paid';
$l['not_paid'] = 'Not Paid';
$l['draft'] = 'Draft';
$l['accepted'] = 'Accepted';
$l['declined'] = 'Declined';
$l['pending'] = 'Pending';
$l['page'] = 'Page';
$l['page_of'] = 'of';
